name: Build & Deploy Angular

# Scatta a ogni push su main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build produzione
        run: npm run build:prod

      - name: Preparo fallback SPA
        run: |
          cp dist/ilreleone-frontend/index.html dist/ilreleone-frontend/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/ilreleone-frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
